# Generated by Django 3.0.8 on 2020-07-02 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_answer_choice_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='choice_id',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='exam_id',
            new_name='exam',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='exam_id',
            new_name='exam',
        ),
    ]
