# Generated by Django 3.0.4 on 2020-03-08 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_auto_20200308_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productcategory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
