# Generated by Django 3.0.4 on 2020-03-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200308_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
    ]
